micronaut:
  application:
    name: cqrs-framework
  executors:
    saga-on-success-actions:
      type: scheduled
      name: saga-on-success-actions
      thread-factory-class: io.micronaut.scheduling.executor.NamedThreadFactory

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: false
    failOnUnknownProperties: false

cqrs:
  scheduler:
    prefix: 'cqrs'
    poolSize: 4

